# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoMoreR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GMServerSDK', :git => 'https://github.com/bOMDIC/Kit_iOS_ServerAPI.git'

  # Pods for GoMoreR

end

target 'MessageIntents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageIntents

end

target 'MessageIntentsUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageIntentsUI

end
